### ISSUE TITLE
array of hash references can't be displayed in debugger

### ISSUE THREAD

**Issue by dseynhae** [richterger/Perl-LanguageServer#136] opened 2022-04-22 18:47 UTC
Consider the simple example, with the array `@objects` of hashreferences:

```Perl
package main 1.0;
use strict;
use warnings;

my @objects = (
  {
    name  => 'object1',
    value => 1
  },
  {
    name  => 'object',
    value => 2
  },
  {
    name  => 'object2',
    value => 3
  },
  {
    name  => 'object',
    value => 4
  },
);

my @objects_filter1 = grep { $_->{name} eq 'object' } @objects;

print @objects_filter1 . "\n";

1;

```

When going through the debugger, each array element is listed as `Invalid variable attributes`.

I filter the array down with a simple grep expression, and the result array `@objects_filter` shows the same problem.

Exploring the arrays in the WATCH window shows that everything is actually working as expected:

![image](https://user-images.githubusercontent.com/54114043/164775776-b4e67d2f-5219-4858-8a48-e482f4928626.png)

**Comment by richterger** [comment] 2022-04-28 05:48
duplicate of #120

**Closed by richterger** 2022-04-28 05:48 UTC
Labels: duplicate
