### ISSUE TITLE
FindBin problems when syntax checking

### ISSUE THREAD

**Issue by syberrus** [richterger/Perl-LanguageServer#123] opened 2021-12-24 19:07 UTC
scripts that use $FindBin::Bin can't be syntax-checked, it is always an error, because $FindBin::Bin is always a project root, because $0 is '-'. Does this plugin feed file content to perl via stdin ? if so, maybe "$0 = 'original file path'" should be inserted as the first line?

**Comment by richterger** [comment] 2022-04-20 09:03
Duplicate of #16

**Closed by richterger** 2022-04-20 09:03 UTC
Labels: bug, duplicate
